title: William Peck # your name (or website title) here
logo: "/images/Photo_Me.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome! I am an aspiring programmer aiming to develop my skills. Currently finishing an MSc in Computing Systems.
  Looking for work or placement opportunities starting in september within game programming / software development / software engineering / software programming.
  <br><br>
  Below lists my experiences and skillset.
  <br><br>
    
  Languages: 
  C#, C++, JavaScript, Python, Xamarin
  
  <br><br>
  
  Development Environment:
  Visual Studio, Andriod Studio, Unity, PyCharm, SQL Server Management Studio, Google Firebase
  
  <br><br>
  
  AI:
  TensorFlow, CNTK, ML Kit, PyTorch
  
  <br><br>
  
  Source Control:
  Github, TortoiseSVN, Github Enterprise
  
  <br><br>
  <a href="https://www.linkedin.com/in/william-peck-1006/">View My LinkedIn Profile</a> 

  
theme: jekyll-theme-minimal

